version: "3"
services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/database
      - ./database/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

  s3:
    container_name: minio-s3
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
    volumes:
      - ./minIO/setup_storage.sh:/setup_storage.sh
