import { neighbors } from 'topojson-client';
import { topology } from './map.topology';

export const createRelationsFromTopology = () => {
  const idRelations = {};
  let currentCountryID;
  let relatedCountryID;
  neighbors(topology.objects.countries.geometries).forEach((countryRelations, index) => {
    currentCountryID = topology.objects.countries.geometries[index].id;
    const localRelations = {};
    countryRelations.forEach((countryNumber) => {
      relatedCountryID = topology.objects.countries.geometries[countryNumber].id;
      localRelations[relatedCountryID] = true;
    });
    idRelations[currentCountryID] = localRelations;
  });
  return idRelations;
};

export const neighbouringRelations = {
  AFG: { CHN: true, IRN: true, PAK: true, TJK: true, TKM: true, UZB: true },
  AGO: { COD: true, COG: true, NAM: true, ZMB: true },
  ALB: { GRC: true, 'CS-KM': true, MKD: true, MNE: true },
  ARE: { OMN: true, SAU: true },
  ARG: { BOL: true, BRA: true, CHL: true, PRY: true, URY: true },
  ARM: { AZE: true, GEO: true, IRN: true, TUR: true },
  AUS: {},
  AUT: { CHE: true, CZE: true, DEU: true, HUN: true, ITA: true, SVK: true, SVN: true },
  AZE: { ARM: true, GEO: true, IRN: true, RUS: true },
  BDI: { COD: true, RWA: true, TZA: true },
  BEL: { DEU: true, FRA: true, LUX: true, NLD: true },
  BEN: { BFA: true, NER: true, NGA: true, TGO: true },
  BFA: { BEN: true, CIV: true, GHA: true, MLI: true, NER: true, TGO: true },
  BGD: { IND: true, MMR: true },
  BGR: { GRC: true, MKD: true, ROU: true, SRB: true, TUR: true },
  BHS: {},
  BIH: { HRV: true, MNE: true, SRB: true },
  BLR: { LTU: true, LVA: true, POL: true, RUS: true, UKR: true },
  BLZ: { GTM: true, MEX: true },
  BMU: {},
  BOL: { ARG: true, BRA: true, CHL: true, PER: true, PRY: true },
  BRA: { ARG: true, BOL: true, COL: true, GUF: true, GUY: true, PER: true, PRY: true, SUR: true, URY: true, VEN: true },
  BRN: { MYS: true },
  BTN: { CHN: true, IND: true },
  BWA: { NAM: true, ZAF: true, ZMB: true, ZWE: true },
  CAF: { CMR: true, COD: true, COG: true, SDN: true, SSD: true, TCD: true },
  CAN: { USA: true },
  CHE: { AUT: true, DEU: true, FRA: true, ITA: true },
  CHL: { ARG: true, BOL: true, PER: true },
  CHN: {
    AFG: true,
    BTN: true,
    IND: true,
    KAZ: true,
    KGZ: true,
    LAO: true,
    MMR: true,
    MNG: true,
    NPL: true,
    PAK: true,
    PRK: true,
    RUS: true,
    TJK: true,
    VNM: true,
  },
  CIV: { BFA: true, GHA: true, GIN: true, LBR: true, MLI: true },
  CMR: { CAF: true, COG: true, GAB: true, GNQ: true, NER: true, NGA: true, TCD: true },
  COD: { AGO: true, BDI: true, CAF: true, COG: true, RWA: true, SSD: true, TZA: true, UGA: true, ZMB: true },
  COG: { AGO: true, CAF: true, CMR: true, COD: true, GAB: true },
  COL: { BRA: true, ECU: true, PAN: true, PER: true, VEN: true },
  CRI: { NIC: true, PAN: true },
  CUB: {},
  CYP: { CYP: true },
  CZE: { AUT: true, DEU: true, POL: true, SVK: true },
  DEU: { AUT: true, BEL: true, CHE: true, CZE: true, DNK: true, FRA: true, LUX: true, NLD: true, POL: true },
  DJI: { ERI: true, ETH: true, '-99': true },
  DNK: { DEU: true },
  DOM: { HTI: true },
  DZA: { LBY: true, MAR: true, MLI: true, MRT: true, NER: true, ESH: true, TUN: true },
  ECU: { COL: true, PER: true },
  EGY: { ISR: true, LBY: true, SDN: true },
  ERI: { DJI: true, ETH: true, SDN: true },
  ESP: { FRA: true, PRT: true },
  EST: { LVA: true, RUS: true },
  ETH: { DJI: true, ERI: true, KEN: true, SDN: true, SSD: true, '-99': true, SOM: true },
  FIN: { NOR: true, RUS: true, SWE: true },
  FJI: {},
  FLK: {},
  FRA: { BEL: true, CHE: true, DEU: true, ESP: true, ITA: true, LUX: true },
  GAB: { CMR: true, COG: true, GNQ: true },
  GBR: { IRL: true },
  GEO: { ARM: true, AZE: true, RUS: true, TUR: true },
  GHA: { BFA: true, CIV: true, TGO: true },
  GIN: { CIV: true, GNB: true, LBR: true, MLI: true, SEN: true, SLE: true },
  GMB: { SEN: true },
  GNB: { GIN: true, SEN: true },
  GNQ: { CMR: true, GAB: true },
  GRC: { ALB: true, BGR: true, MKD: true, TUR: true },
  GRL: {},
  GTM: { BLZ: true, HND: true, MEX: true, SLV: true },
  GUF: { BRA: true, SUR: true },
  GUY: { BRA: true, SUR: true, VEN: true },
  HND: { GTM: true, NIC: true, SLV: true },
  HRV: { BIH: true, HUN: true, MNE: true, SRB: true, SVN: true },
  HTI: { DOM: true },
  HUN: { AUT: true, HRV: true, ROU: true, SRB: true, SVK: true, SVN: true, UKR: true },
  IDN: { MYS: true, PNG: true, TLS: true },
  IND: { BGD: true, BTN: true, CHN: true, MMR: true, NPL: true, PAK: true },
  IRL: { GBR: true },
  IRN: { AFG: true, ARM: true, AZE: true, IRQ: true, PAK: true, TKM: true, TUR: true },
  IRQ: { IRN: true, JOR: true, KWT: true, SAU: true, SYR: true, TUR: true },
  ISL: {},
  ISR: { EGY: true, JOR: true, LBN: true, SYR: true, PSE: true },
  ITA: { AUT: true, CHE: true, FRA: true, SVN: true },
  JAM: {},
  JOR: { IRQ: true, ISR: true, SAU: true, SYR: true, PSE: true },
  JPN: {},
  KAZ: { CHN: true, KGZ: true, RUS: true, TKM: true, UZB: true },
  KEN: { ETH: true, SSD: true, SOM: true, TZA: true, UGA: true },
  KGZ: { CHN: true, KAZ: true, TJK: true, UZB: true },
  KHM: { LAO: true, THA: true, VNM: true },
  KOR: { PRK: true },
  'CS-KM': { ALB: true, MKD: true, MNE: true, SRB: true },
  KWT: { IRQ: true, SAU: true },
  LAO: { CHN: true, KHM: true, MMR: true, THA: true, VNM: true },
  LBN: { ISR: true, SYR: true },
  LBR: { CIV: true, GIN: true, SLE: true },
  LBY: { DZA: true, EGY: true, NER: true, SDN: true, TCD: true, TUN: true },
  LKA: {},
  LSO: { ZAF: true },
  LTU: { BLR: true, LVA: true, POL: true, RUS: true },
  LUX: { BEL: true, DEU: true, FRA: true },
  LVA: { BLR: true, EST: true, LTU: true, RUS: true },
  MAR: { DZA: true, ESH: true },
  MDA: { ROU: true, UKR: true },
  MDG: {},
  MEX: { BLZ: true, GTM: true, USA: true },
  MKD: { ALB: true, BGR: true, GRC: true, 'CS-KM': true, SRB: true },
  MLI: { BFA: true, CIV: true, DZA: true, GIN: true, MRT: true, NER: true, SEN: true },
  MLT: {},
  MMR: { BGD: true, CHN: true, IND: true, LAO: true, THA: true },
  MNE: { ALB: true, BIH: true, HRV: true, 'CS-KM': true, SRB: true },
  MNG: { CHN: true, RUS: true },
  MOZ: { MWI: true, SWZ: true, TZA: true, ZAF: true, ZMB: true, ZWE: true },
  MRT: { DZA: true, MLI: true, ESH: true, SEN: true },
  MWI: { MOZ: true, TZA: true, ZMB: true },
  MYS: { BRN: true, IDN: true, THA: true },
  NAM: { AGO: true, BWA: true, ZAF: true, ZMB: true },
  NCL: {},
  NER: { BEN: true, BFA: true, CMR: true, DZA: true, LBY: true, MLI: true, NGA: true, TCD: true },
  NGA: { BEN: true, CMR: true, NER: true },
  NIC: { CRI: true, HND: true },
  NLD: { BEL: true, DEU: true },
  NOR: { FIN: true, RUS: true, SWE: true },
  NPL: { CHN: true, IND: true },
  NZL: {},
  OMN: { ARE: true, SAU: true, YEM: true },
  PAK: { AFG: true, CHN: true, IND: true, IRN: true },
  PAN: { COL: true, CRI: true },
  PER: { BOL: true, BRA: true, CHL: true, COL: true, ECU: true },
  PHL: {},
  PNG: { IDN: true },
  POL: { BLR: true, CZE: true, DEU: true, LTU: true, RUS: true, SVK: true, UKR: true },
  PRI: {},
  PRK: { CHN: true, KOR: true, RUS: true },
  PRT: { ESP: true },
  PRY: { ARG: true, BOL: true, BRA: true },
  QAT: { SAU: true },
  ROU: { BGR: true, HUN: true, MDA: true, SRB: true, UKR: true },
  RUS: {
    AZE: true,
    BLR: true,
    CHN: true,
    EST: true,
    FIN: true,
    GEO: true,
    KAZ: true,
    LTU: true,
    LVA: true,
    MNG: true,
    NOR: true,
    POL: true,
    PRK: true,
    UKR: true,
  },
  RWA: { BDI: true, COD: true, TZA: true, UGA: true },
  ESH: { DZA: true, MAR: true, MRT: true },
  SAU: { ARE: true, IRQ: true, JOR: true, KWT: true, OMN: true, QAT: true, YEM: true },
  SDN: { CAF: true, EGY: true, ERI: true, ETH: true, LBY: true, SSD: true, TCD: true },
  SSD: { CAF: true, COD: true, ETH: true, KEN: true, SDN: true, UGA: true },
  SEN: { GIN: true, GMB: true, GNB: true, MLI: true, MRT: true },
  SLB: {},
  SLE: { GIN: true, LBR: true },
  SLV: { GTM: true, HND: true },
  '-99': { DJI: true, ETH: true, SOM: true },
  SOM: { ETH: true, KEN: true, '-99': true },
  SRB: { BGR: true, BIH: true, HRV: true, HUN: true, 'CS-KM': true, MKD: true, MNE: true, ROU: true },
  SUR: { BRA: true, GUF: true, GUY: true },
  SVK: { AUT: true, CZE: true, HUN: true, POL: true, UKR: true },
  SVN: { AUT: true, HRV: true, HUN: true, ITA: true },
  SWE: { FIN: true, NOR: true },
  SWZ: { MOZ: true, ZAF: true },
  SYR: { IRQ: true, ISR: true, JOR: true, LBN: true, TUR: true },
  TCD: { CAF: true, CMR: true, LBY: true, NER: true, SDN: true },
  TGO: { BEN: true, BFA: true, GHA: true },
  THA: { KHM: true, LAO: true, MMR: true, MYS: true },
  TJK: { AFG: true, CHN: true, KGZ: true, UZB: true },
  TKM: { AFG: true, IRN: true, KAZ: true, UZB: true },
  TLS: { IDN: true },
  TTO: {},
  TUN: { DZA: true, LBY: true },
  TUR: { ARM: true, BGR: true, GEO: true, GRC: true, IRN: true, IRQ: true, SYR: true },
  TWN: {},
  TZA: { BDI: true, COD: true, KEN: true, MOZ: true, MWI: true, RWA: true, UGA: true, ZMB: true },
  UGA: { COD: true, KEN: true, RWA: true, SSD: true, TZA: true },
  UKR: { BLR: true, HUN: true, MDA: true, POL: true, ROU: true, RUS: true, SVK: true },
  URY: { ARG: true, BRA: true },
  USA: { CAN: true, MEX: true },
  UZB: { AFG: true, KAZ: true, KGZ: true, TJK: true, TKM: true },
  VEN: { BRA: true, COL: true, GUY: true },
  VNM: { CHN: true, KHM: true, LAO: true },
  VUT: {},
  PSE: { ISR: true, JOR: true },
  YEM: { OMN: true, SAU: true },
  ZAF: { BWA: true, LSO: true, MOZ: true, NAM: true, SWZ: true, ZWE: true },
  ZMB: { AGO: true, BWA: true, COD: true, MOZ: true, MWI: true, NAM: true, TZA: true, ZWE: true },
  ZWE: { BWA: true, MOZ: true, ZAF: true, ZMB: true },
};
